services:
  mcp-for-docs:
    image: appwrite/mcp-for-docs
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - 1234:1234
    env_file:
      - .env