services:
  mcp-for-docs:
    image: appwrite/mcp-for-docs
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - OPENAI_API_KEY
    ports:
      - 1234:1234
    env_file:
      - .env

secrets:
  OPENAI_API_KEY:
    environment: OPENAI_API_KEY
